# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= darwin18.7.0
MACHINETYPE	:= x86_64
PLATFORM	:= x86_64-apple-darwin18.7.0
FULLOSTYPE	:= apple-darwin18.7.0
